spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/spring}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  cache:
    type: simple

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.attractions: DEBUG
